version: "3"
services:
  application:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: sample
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    environment:
      TZ: Asia/Seoul